/* This file is automatically generated. DO NOT EDIT! */

#ifndef _laplac2_h
#define _laplac2_h


#include <rsf.h>


void laplac2_init(int m1, int m2);
/*< initialize with data size >*/


void laplac2(int   np, 
             int   nr, 
             sf_complex *p, 
             sf_complex *r);
/*< linear operator >*/

#endif
